#!/usr/bin/env python3

# Netowrk config
SERVER_ADDR = 'localhost'
SERVER_PORT = 18000
RECV_BUFFER = 128 * 1024
CONNECTIONMAX = 5
PACKETVER = 1
HEADER_SIZE = 8

# Mining config
INIWAIT_TIME = 2
RANBROAD_TIME = 10
COM_INTERVAL = 1800
CLEAR_TIME = 3
BLOCK_INTERVAL = 10

# Measure config
MEASURE_INTERVAL = 30


TIME_INTERVAL = 5 # Seconds

